sudo: required

language: python
python:
    - "2.7"

services:
  - docker

before_install:
    - docker pull rootproject/root-ubuntu16:snapshot

script:
    - docker run --rm -it rootproject/root-ubuntu16:snapshot /bin/sh -c "source /usr/local/bin/thisroot.sh;cd;git clone https://github.com/piberger/Xbb.git;cd Xbb/python/test;python ./run_all.py"
